### ISSUE TITLE
Container doesn't start with mount directory 

### ISSUE THREAD

**Issue by lrgrz** [gvenzl/oci-oracle-xe#191] opened 2023-03-09 17:51 UTC
I'm trying to start the container using volume mounts:
1) -v /home/oracle/oradata:/opt/oracle/oradata
2) --tmpfs /opt/oracle/oradata:uid=54321,gid=54321 

In both cases commands fails with following output:
```
~ docker run -p 1521:1521 --name oracle -v /home/oracle/oradata:/opt/oracle/oradata -e ORACLE_PASSWORD=oracle --rm gvenzl/oracle-xe:21-slim-faststart
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: starting up Oracle Database...

LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 09-MAR-2023 17:18:26

Copyright (c) 1991, 2021, Oracle.  All rights reserved.

Starting /opt/oracle/product/21c/dbhomeXE/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 21.0.0.0.0 - Production
System parameter file is /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/9deea6bf6385/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                09-MAR-2023 17:18:26
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/9deea6bf6385/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
ORACLE instance started.

Total System Global Area 1241512272 bytes
Fixed Size		    9685328 bytes
Variable Size		  637534208 bytes
Database Buffers	  587202560 bytes
Redo Buffers		    7090176 bytes
ORA-00205: error in identifying control file, check alert log for more info
```

Oradata seems to have proper permissions:
```
~ ls -la /home/oracle/
total 12
drwxr-xr-x 3 54321 54321 4096 mar  9 18:17 .
drwxr-xr-x 4 root  root  4096 mar  9 18:17 ..
drwxr-xr-x 3 54321 54321 4096 mar  9 18:18 oradata
```
Few files has been created/copied successfully to mounted dir:
```
~ ls -la /home/oracle/oradata/dbconfig/XE/
total 28
drwxr-xr-x 2 54321 54321 4096 mar  9 18:18 .
drwxr-xr-x 3 54321 54321 4096 mar  9 18:18 ..
-rw-r--r-- 1 54321 54322  214 lut  6 03:37 listener.ora
-rw-r----- 1 54321 54321 2048 lut  6 03:31 orapwXE
-rw-r----- 1 54321 54321 3584 lut  6 03:51 spfileXE.ora
-rw-r--r-- 1 54321 54322  138 lut  6 03:37 sqlnet.ora
-rw-r--r-- 1 54321 54322  552 lut  6 03:37 tnsnames.ora
```

Logs from `/opt/oracle/diag/rdbms/xe/XE/trace/alert_XE.log` since 2023-03-09
```
Starting ORACLE instance (normal) (OS id: 28)
2023-03-09T16:08:17.814780+00:00
****************************************************
 Sys-V shared memory will be used for creating SGA 
 ****************************************************
2023-03-09T16:08:17.815354+00:00
**********************************************************************
2023-03-09T16:08:17.815421+00:00
Dump of system resources acquired for SHARED GLOBAL AREA (SGA) 

2023-03-09T16:08:17.815527+00:00
 Per process system memlock (soft) limit = 64K
2023-03-09T16:08:17.815590+00:00
 Expected per process system memlock (soft) limit to lock
 instance MAX SHARED GLOBAL AREA (SGA) into memory: 1186M
2023-03-09T16:08:17.815713+00:00
 Available system pagesizes:
  4K, 2048K 
2023-03-09T16:08:17.815835+00:00
 Supported system pagesize(s):
2023-03-09T16:08:17.815897+00:00
  PAGESIZE  AVAILABLE_PAGES  EXPECTED_PAGES  ALLOCATED_PAGES  ERROR(s)
2023-03-09T16:08:17.815961+00:00
        4K       Configured               4        On-Demand        NONE
2023-03-09T16:08:17.816060+00:00
     2048K                0             593        On-Demand        NONE
2023-03-09T16:08:17.816123+00:00
RECOMMENDATION:
2023-03-09T16:08:17.816186+00:00
 1. For optimal performance, configure system with expected number 
 of pages for every supported system pagesize prior to the next 
 instance restart operation.
2023-03-09T16:08:17.817562+00:00
 2. Increase per process memlock (soft) limit to at least 1186MB
 to lock 100% of SHARED GLOBAL AREA (SGA) pages into physical memory
2023-03-09T16:08:17.817694+00:00
**********************************************************************
Using an SGA granule size of 16MB
Memory protection keys NOT enabled.
2023-03-09T16:08:17.858662+00:00
Errors in file /opt/oracle/diag/rdbms/xe/XE/trace/XE_ora_28.trc:
ORA-27167: Attempt to determine if Oracle binary image is stored on remote server failed
ORA-27300: OS system dependent operation:parse_df failed with status: 2
ORA-27301: OS failure message: No such file or directory
ORA-27302: failure occurred at: parse failed
ORA-27303: additional information: Filesystem     1K-blocks     Used Available Use% Mounted on
overlay        102054872 57740000  39084588  60% /
Image consistency checking encountered an error, checking disabled
LICENSE_MAX_SESSION = 0
LICENSE_SESSIONS_WARNING = 0
Initial number of CPU is 2
Number of processor cores in the system is 4
Number of processor sockets in the system is 1
Capability Type : Network 
capabilities requested : F detected : 0 Simulated : 0
Capability Type : Runtime Environment 
capabilities requested : 400000FF detected : 40000000 Simulated : 0
Capability Type : Engineered Systems 
capabilities requested : F detected : 0 Simulated : 0
Capability Type : Database Test 
capabilities requested : 3 detected : 0 Simulated : 0
Capability Type : Database Editions 
capabilities requested : 1CC detected : 10 Simulated : 0
Using LOG_ARCHIVE_DEST_1 parameter default value as /opt/oracle/homes/OraDBHome21cXE/dbs/arch
Autotune of undo retention is turned on. 
IMODE=BR
ILAT =51
LICENSE_MAX_USERS = 0
SYS auditing is disabled
NOTE: remote asm mode is local (mode 0x1; from cluster type)
NOTE: Using default ASM root directory ASM
NOTE: remote asm mode is local (mode 0x1; from cluster type)
NOTE: Cluster configuration type = NONE [2]
NOTE: initializing MDS service with 1 containers
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0.
ORACLE_HOME:    /opt/oracle/product/21c/dbhomeXE
System name:	Linux
Node name:	1c70b782c972
Release:	5.15.0-67-generic
Version:	#74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023
Machine:	x86_64
Using parameter settings in server-side spfile /opt/oracle/dbs/spfileXE.ora
System parameters with non-default values:
  processes                = 300
  cpu_count                = 2
  nls_language             = "AMERICAN"
  nls_territory            = "AMERICA"
  sga_target               = 1184M
  control_files            = "/opt/oracle/oradata/XE/control01.ctl"
  control_files            = "/opt/oracle/oradata/XE/control02.ctl"
  db_block_size            = 8192
  compatible               = "21.0.0"
  undo_tablespace          = "UNDOTBS1"
  remote_login_passwordfile= "EXCLUSIVE"
  audit_sys_operations     = FALSE
  dispatchers              = "(PROTOCOL=TCP) (SERVICE=XEXDB)"
  shared_servers           = 0
  local_listener           = ""
  audit_file_dest          = "/opt/oracle/admin/XE/adump"
  audit_trail              = "NONE"
  db_name                  = "XE"
  open_cursors             = 300
  pga_aggregate_target     = 392M
  _dmm_blas_library        = "libora_netlib.so"
  control_management_pack_access= "DIAGNOSTIC+TUNING"
  spatial_vector_acceleration= FALSE
  diagnostic_dest          = "/opt/oracle"
  enable_pluggable_database= TRUE
  common_user_prefix       = ""
Errors in file /opt/oracle/diag/rdbms/xe/XE/trace/XE_ora_28.trc  (incident=1):
ORA-00600: internal error code, arguments: [OSDEP_INTERNAL], [], [], [], [], [], [], [], [], [], [], []
ORA-27302: failure occurred at: skgpiidcompa
Incident details in: /opt/oracle/diag/rdbms/xe/XE/incident/incdir_1/XE_ora_28_i1.trc
2023-03-09T16:08:18.941104+00:00
Use ADRCI or Support Workbench to package the incident.
See Note 411.1 at My Oracle Support for error and packaging details.
2023-03-09T16:08:18.941254+00:00
Errors in file /opt/oracle/diag/rdbms/xe/XE/trace/XE_ora_28.trc:
ORA-00600: internal error code, arguments: [OSDEP_INTERNAL], [], [], [], [], [], [], [], [], [], [], []
ORA-27302: failure occurred at: skgpiidcompa
2023-03-09T16:08:18.941325+00:00
WARNING: Oracle dynamic library mismatch detected.
 Libraries of new process does not match libraries which started instance
issue alter system set "_disable_image_check" = true to disable these messages
2023-03-09T16:08:18.942639+00:00
Oracle instance running with ODM in SGA: FSDirect ODM Library Version 1.0 
Broadcast on commit is enabled and is using Message mode.
Starting background process PMON
2023-03-09T16:08:19.685794+00:00
PMON started with pid=2, OS id=32 
Starting background process CLMN
2023-03-09T16:08:19.698829+00:00
CLMN started with pid=3, OS id=36 
Starting background process PSP0
2023-03-09T16:08:19.731257+00:00
PSP0 started with pid=4, OS id=40 
Starting background process VKTM
2023-03-09T16:08:19.788965+00:00
Errors in file /opt/oracle/diag/rdbms/xe/XE/trace/XE_vktm_44.trc  (incident=42) (PDBNAME=CDB$ROOT):
ORA-00800: soft external error, arguments: [Set Priority Failed], [VKTM], [Check traces and OS configuration], [Check Oracle document and MOS notes], []
Incident details in: /opt/oracle/diag/rdbms/xe/XE/incident/incdir_42/XE_vktm_44_i42.trc
2023-03-09T16:08:19.790691+00:00
Error attempting to elevate VKTM's priority: no further priority changes will be attempted for this process
VKTM started with pid=5, OS id=44 
Starting background process GEN0
VKTM running at (100ms) precision 
2023-03-09T16:08:19.844731+00:00
GEN0 started with pid=6, OS id=50 
Starting background process MMAN
2023-03-09T16:08:19.857667+00:00
MMAN started with pid=7, OS id=54 
Starting background process GEN1
Starting background process GEN2
2023-03-09T16:08:19.885043+00:00
GEN2 started with pid=11, OS id=62 
Starting background process VOSD
Starting background process DIAG
Starting background process OFSD
Starting background process DBRM
Starting background process VKRM
Starting background process SVCB
Starting background process PMAN
Starting background process DIA0
Starting background process DBW0
Starting background process LGWR
Starting background process CKPT
Starting background process SMON
Starting background process SMCO
Starting background process RECO
Starting background process LREG
Starting background process PXMN
Starting background process FENC
Starting background process MMON
Starting background process MMNL
2023-03-09T16:08:19.892215+00:00
GEN1 started with pid=9, OS id=60_65 
2023-03-09T16:08:19.904857+00:00
DIAG started with pid=13, OS id=69 
2023-03-09T16:08:19.907262+00:00
VOSD started with pid=12, OS id=67 
2023-03-09T16:08:19.908517+00:00
Dumping diagnostic data in directory=[cdmp_20230309160819], requested by (instance=1, osid=28), summary=[incident=1].
2023-03-09T16:08:19.925089+00:00
OFSD started with pid=14, OS id=71_76 
2023-03-09T16:08:19.925932+00:00
Oracle running with ofslib:'Oracle File Server Library' version=2 inc=1
2023-03-09T16:08:19.937374+00:00
VKRM started with pid=17, OS id=78 
2023-03-09T16:08:19.943737+00:00
SVCB started with pid=18, OS id=81 
2023-03-09T16:08:19.949054+00:00
DBRM started with pid=16, OS id=75 
2023-03-09T16:08:19.960392+00:00
DIA0 started with pid=20, OS id=86 
2023-03-09T16:08:19.971490+00:00
PMAN started with pid=19, OS id=83 
2023-03-09T16:08:19.979805+00:00
DBW0 started with pid=21, OS id=88 
2023-03-09T16:08:19.985446+00:00
SMON started with pid=24, OS id=97 
2023-03-09T16:08:19.988620+00:00
CKPT started with pid=23, OS id=93 
2023-03-09T16:08:19.990362+00:00
SMCO started with pid=25, OS id=99 
2023-03-09T16:08:19.996275+00:00
RECO started with pid=26, OS id=105 
2023-03-09T16:08:20.005218+00:00
LREG started with pid=27, OS id=111 
2023-03-09T16:08:20.009090+00:00
PXMN started with pid=28, OS id=114 
2023-03-09T16:08:20.019085+00:00
Errors in file /opt/oracle/diag/rdbms/xe/XE/trace/XE_lgwr_90.trc  (incident=178) (PDBNAME=CDB$ROOT):
ORA-00800: soft external error, arguments: [Set Priority Failed], [LGWR], [Check traces and OS configuration], [Check Oracle document and MOS notes], []
Incident details in: /opt/oracle/diag/rdbms/xe/XE/incident/incdir_178/XE_lgwr_90_i178.trc
2023-03-09T16:08:20.020900+00:00
Error attempting to elevate LGWR's priority: no further priority changes will be attempted for this process
2023-03-09T16:08:20.022153+00:00
MMON started with pid=30, OS id=120 
2023-03-09T16:08:20.032179+00:00
MMNL started with pid=31, OS id=122 
2023-03-09T16:08:20.035204+00:00
FENC started with pid=29, OS id=117 
LGWR started with pid=22, OS id=90 
2023-03-09T16:08:20.064186+00:00
starting up 1 dispatcher(s) for network address '(ADDRESS=(PARTIAL=YES)(PROTOCOL=TCP))'...
Warning: Shared server clients will not be able to connect because SHARED_SERVERS is 0
2023-03-09T16:08:20.087811+00:00
LGWR slave LG00 created with pid=41, OS pid=140
Starting background process TMON
2023-03-09T16:08:20.097595+00:00
TMON started with pid=42, OS id=142 
2023-03-09T16:08:20.098530+00:00
RACD notifier running level=0
ORACLE_BASE from environment = /opt/oracle
PMEM FILESTORE feature is only available in Oracle Database Enterprise Edition.
2023-03-09T16:08:20.125550+00:00
LGWR slave LG01 created with pid=44, OS pid=147
2023-03-09T16:08:20.144339+00:00
ALTER DATABASE   MOUNT
2023-03-09T16:08:20.194686+00:00
ORA-00210: cannot open the specified control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control02.ctl'
ORA-27037: unable to obtain file status
Linux-x86_64 Error: 2: No such file or directory
Additional information: 7
ORA-00210: cannot open the specified control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control01.ctl'
ORA-27037: unable to obtain file status
Linux-x86_64 Error: 2: No such file or directory
Additional information: 7
ORA-205 signalled during: ALTER DATABASE   MOUNT...
```

**Comment by gvenzl** [comment] 2023-03-12 22:05
Hi @lrgrz,

Thanks a lot for using these images!

It appears that your volume is in an inconsistent state.
The configuration files are present, as per your output:

```
~ ls -la /home/oracle/oradata/dbconfig/XE/
total 28
drwxr-xr-x 2 54321 54321 4096 mar  9 18:18 .
drwxr-xr-x 3 54321 54321 4096 mar  9 18:18 ..
-rw-r--r-- 1 54321 54322  214 lut  6 03:37 listener.ora
-rw-r----- 1 54321 54321 2048 lut  6 03:31 orapwXE
-rw-r----- 1 54321 54321 3584 lut  6 03:51 spfileXE.ora
-rw-r--r-- 1 54321 54322  138 lut  6 03:37 sqlnet.ora
-rw-r--r-- 1 54321 54322  552 lut  6 03:37 tnsnames.ora
```

But the control and probably database files are not:

```
ORA-00210: cannot open the specified control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control02.ctl'
ORA-27037: unable to obtain file status
Linux-x86_64 Error: 2: No such file or directory
Additional information: 7
ORA-00210: cannot open the specified control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control01.ctl'
ORA-27037: unable to obtain file status
Linux-x86_64 Error: 2: No such file or directory
```

Do you have any other directories in `/home/oracle/oradata/`?

**Comment by shirishpandharikar** [comment] 2023-05-07 07:43
@gvenzl I have a similar issue. Maybe I'm doing something wrong with my limited understanding and my first time running Oracle in Docker. Below is my configuration

```
version: "3.8"

services:

  oracle:
    image: gvenzl/oracle-xe:21-faststart
    container_name: oracle
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: <your password>
    volumes:
      - ./oracle-data:/opt/oracle/oradata
```

Permission for the volume mount
```
drwxrwxr-x 3   54321   54321 4096 May  7 13:05 oracle-data
```

```
Creating network "oracle-xe-21_default" with the default driver
Creating oracle ... done
Attaching to oracle
oracle    | CONTAINER: starting up...
oracle    | CONTAINER: first database startup, initializing...
oracle    | CONTAINER: starting up Oracle Database...
oracle    | 
oracle    | LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 07-MAY-2023 07:35:18
oracle    | 
oracle    | Copyright (c) 1991, 2021, Oracle.  All rights reserved.
oracle    | 
oracle    | Starting /opt/oracle/product/21c/dbhomeXE/bin/tnslsnr: please wait...
oracle    | 
oracle    | TNSLSNR for Linux: Version 21.0.0.0.0 - Production
oracle    | System parameter file is /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
oracle    | Log messages written to /opt/oracle/diag/tnslsnr/76297185a932/listener/alert/log.xml
oracle    | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
oracle    | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
oracle    | 
oracle    | Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
oracle    | STATUS of the LISTENER
oracle    | ------------------------
oracle    | Alias                     LISTENER
oracle    | Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
oracle    | Start Date                07-MAY-2023 07:35:18
oracle    | Uptime                    0 days 0 hr. 0 min. 0 sec
oracle    | Trace Level               off
oracle    | Security                  ON: Local OS Authentication
oracle    | SNMP                      OFF
oracle    | Default Service           XE
oracle    | Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
oracle    | Listener Log File         /opt/oracle/diag/tnslsnr/76297185a932/listener/alert/log.xml
oracle    | Listening Endpoints Summary...
oracle    |   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
oracle    |   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
oracle    | The listener supports no services
oracle    | The command completed successfully
oracle    | ORACLE instance started.
oracle    | 
oracle    | Total System Global Area 1241512272 bytes
oracle    | Fixed Size		    9685328 bytes
oracle    | Variable Size		  603979776 bytes
oracle    | Database Buffers	  620756992 bytes
oracle    | Redo Buffers		    7090176 bytes
oracle    | ORA-00205: error in identifying control file, check alert log for more info
oracle    | 
oracle    | 
oracle exited with code 205
```

Running the below command works as expected
```
docker run -d -p 1521:1521 -e ORACLE_PASSWORD=<your password> -v oracle-volume:/opt/oracle/oradata gvenzl/oracle-xe:21-faststart
```

I also tried with pre-created volumes and it seems to work as expected.

**Comment by gvenzl** [comment] 2023-05-13 17:41
Hi @shirishpandharikar,

This also looks like the volume is in an inconsistent state, i.e. some files are in the volume but some are not.

Could you please do a `find ./oracle-data` (list all files in the `oracle-data` volume and the `docker logs oracle` output?

**Comment by shirishpandharikar** [comment] 2023-05-15 07:16
@gvenzl Here are the steps I followed with the slim image this time

```
version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0-slim-faststart
    container_name: oracle
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: <password>
    volumes:
      - ./oracle-data:/opt/oracle/oradata
```

It fails with below message
```
Creating oracle ... done
Attaching to oracle
oracle    | CONTAINER: starting up...
oracle    | CONTAINER: first database startup, initializing...
oracle    | mkdir: cannot create directory '/opt/oracle/oradata/dbconfig': Permission denied
oracle exited with code 1
```
This time the volume is empty. Docker logs are as below
```
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
mkdir: cannot create directory '/opt/oracle/oradata/dbconfig': Permission denied
```
Change ownership/permission of the volume with below command
```
sudo chown 54321:54321 oracle-data -R
sudo chmod +x oracle-data -R
```
After changing the ownership/permissions below is the log
```
Starting oracle ... done
Attaching to oracle
oracle    | CONTAINER: starting up...
oracle    | CONTAINER: first database startup, initializing...
oracle    | CONTAINER: starting up Oracle Database...
oracle    | 
oracle    | LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 15-MAY-2023 07:13:00
oracle    | 
oracle    | Copyright (c) 1991, 2021, Oracle.  All rights reserved.
oracle    | 
oracle    | Starting /opt/oracle/product/21c/dbhomeXE/bin/tnslsnr: please wait...
oracle    | 
oracle    | TNSLSNR for Linux: Version 21.0.0.0.0 - Production
oracle    | System parameter file is /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
oracle    | Log messages written to /opt/oracle/diag/tnslsnr/eed996c58880/listener/alert/log.xml
oracle    | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
oracle    | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
oracle    | 
oracle    | Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
oracle    | STATUS of the LISTENER
oracle    | ------------------------
oracle    | Alias                     LISTENER
oracle    | Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
oracle    | Start Date                15-MAY-2023 07:13:00
oracle    | Uptime                    0 days 0 hr. 0 min. 0 sec
oracle    | Trace Level               off
oracle    | Security                  ON: Local OS Authentication
oracle    | SNMP                      OFF
oracle    | Default Service           XE
oracle    | Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
oracle    | Listener Log File         /opt/oracle/diag/tnslsnr/eed996c58880/listener/alert/log.xml
oracle    | Listening Endpoints Summary...
oracle    |   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
oracle    |   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
oracle    | The listener supports no services
oracle    | The command completed successfully
oracle    | ORACLE instance started.
oracle    | 
oracle    | Total System Global Area 1241512272 bytes
oracle    | Fixed Size		    9685328 bytes
oracle    | Variable Size		  603979776 bytes
oracle    | Database Buffers	  620756992 bytes
oracle    | Redo Buffers		    7090176 bytes
oracle    | ORA-00205: error in identifying control file, check alert log for more info
oracle    | 
oracle    | 
oracle exited with code 205
```
Below are the contents of the `oracle-data` volume
```
./oracle-data
./oracle-data/dbconfig
./oracle-data/dbconfig/XE
./oracle-data/dbconfig/XE/listener.ora
./oracle-data/dbconfig/XE/spfileXE.ora
./oracle-data/dbconfig/XE/orapwXE
./oracle-data/dbconfig/XE/tnsnames.ora
./oracle-data/dbconfig/XE/sqlnet.ora
```

**Comment by gvenzl** [comment] 2023-05-16 05:34
Thanks a lot, @shirishpandharikar,

I think I know now what's going on. I believe you are running into the very same issue as I have reproduced over at https://github.com/gvenzl/oci-oracle-xe/issues/198#issuecomment-1546728622, namely that Docker doesn't copy the contents of folders inside the container out into the volume for host-only volumes.
Hence using a volume `./oracle-data` leads to all the database files disappearing when the container is started.

However, when using named volumes, Docker does copy the contents from the folder inside the container into the volume.
Could you please try the following, I bet this will work:

```yaml
version: "3.8"
volumes:
  oracle-data:
services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0-slim-faststart
    container_name: oracle
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: <password>
    volumes:
      - oracle-data:/opt/oracle/oradata
```

**Comment by shirishpandharikar** [comment] 2023-05-16 11:51
@gvenzl I've already tried using a named volume like mentioned in my earlier comment/reply and it certainly works. When using database like PostgreSQL host-only volumes certainly seem to work. Was expecting a similar behaviour here as well. Creating a named volume is certainly possible but is manual step and needs to be done separately

**Comment by gvenzl** [comment] 2023-05-16 15:41
Hi @shirishpandharikar,

Ah yes, you did indeed! Apologies, I missed that line late last night when I replied.

Unfortunately, there is no container magic that can be done here.
If an image has a folder with files and these files disappear, there is not much that can be done anymore once the container is started.

I brought this up with Docker several times and always got the same answer: "_This is just how Linux mounts work, if you want to preserve the files inside a folder, use the recommended named volumes_".

You'd run into the same issue if you were to just mount over `/usr` or, for PostgreSQL, over `/usr/lib/postgresql`:

```
gvenzl@gvenzl-mac test % podman run --name test-postgres -v ./pg:/usr/lib/postgresql -e POSTGRES_PASSWORD=password postgres
/usr/local/bin/docker-entrypoint.sh: line 92: initdb: command not found
```

Regarding the same behavior, PostgreSQL doesn't provide an image with the database files already created in it. Hence the `/var/lib/postgresql/data` folder is empty.
You can still get a similar behavior by using the equivalent non-faststart image `gvenzl/oracle-xe:21.3.0-slim`, where there too the `/opt/oracle/oradata` folder is empty.
Of course, file permissions still come into play, I can see why Docker recommends named volumes:

```
[gvenzl@localhost test]$ mkdir oradata
[gvenzl@localhost test]$ chmod -R 777 oradata
[gvenzl@localhost test]$ podman run --name test-oracle -v ./oradata:/opt/oracle/oradata:rw -e ORACLE_RANDOM_PASSWORD=y gvenzl/oracle-xe:slim
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: uncompressing database data files, please wait...
CONTAINER: done uncompressing database data files, duration: 4 seconds.
CONTAINER: starting up Oracle Database...

LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 16-MAY-2023 15:40:25

Copyright (c) 1991, 2021, Oracle.  All rights reserved.

Starting /opt/oracle/product/21c/dbhomeXE/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 21.0.0.0.0 - Production
System parameter file is /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/84fef4ea42b1/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                16-MAY-2023 15:40:25
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/84fef4ea42b1/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
ORACLE instance started.

Total System Global Area 1610612080 bytes
Fixed Size		    9686384 bytes
Variable Size		  620756992 bytes
Database Buffers	  973078528 bytes
Redo Buffers		    7090176 bytes
Database mounted.
Database opened.

CONTAINER: Resetting SYS and SYSTEM passwords.

User altered.


User altered.

############################################
ORACLE PASSWORD FOR SYS AND SYSTEM: YzFmYzJi
############################################

#########################
DATABASE IS READY TO USE!
#########################
```

Hope this helps!

**Comment by shirishpandharikar** [comment] 2023-05-16 15:59
@gvenzl Ahh! Now I get it. I guess we will have to live with it.
Thank you so much for the detailed explanation.

**Comment by gvenzl** [comment] 2023-05-26 04:33
You are very welcome, @shirishpandharikar!

I'll close this issue for now, if @lrgrz or you have more questions or insights, feel free to reopen it.

**Closed by gvenzl** 2023-05-26 04:33 UTC
Labels: bug, invalid

**Comment by hohwille** [comment] 2023-11-16 14:54
Sorry for posting to closed bug, but I had the same problem and tried with named volume but got this error: 
```
docker: Error response from daemon: failed to mount local volume: mount C:/Ora21Slim/Oracle/datafiles/oradata:/var/lib/docker/volumes/oracle-volume/_data: no such device.
See 'docker run --help'.
```
Maybe it would be worth to document this named volume example in your README to prevent stupid users like me getting it wrong ;)
This is what I did before:
```
docker volume create --opt type=local --opt device=C:/Ora21Slim/Oracle/datafiles/oradata oracle-volume
```
And for the docker run I added ` -v oracle-volume:/opt/oracle/oradata:rw`.
That is what I understood from reading your README and this issue. Maybe I got something wrong.
Anyway thanks for making this - taming Oracle DB is quite a challenge of its own!

BTW: official oracle-docker-images are using `ORACLE_PWD` as env variable and you are using `ORACLE_PASSWORD`. Could you consider also supporting `ORACLE_PWD` to allow seamless switch?
