### ISSUE TITLE
Image crashes on startup with ORA-03113: end-of-file on communication channel

### ISSUE THREAD

**Issue by HenrikDK** [gvenzl/oci-oracle-xe#60] opened 2021-11-28 20:28 UTC
Both latest and 18 images are crashing on startup

In this example, I'm running this command: 

```
docker run -e "ORACLE_PASSWORD=<some-pw>" \
-p 1521:1521 --name oxsql \
-d gvenzl/oracle-xe:18-slim
```

After a while the container exits on its own. and when I run docker logs:

```
docker logs oxsql
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: uncompressing database data files, please wait...
CONTAINER: done uncompressing database data files, duration: 26 seconds.
CONTAINER: starting up Oracle Database...

LSNRCTL for Linux: Version 18.0.0.0.0 - Production on 28-NOV-2021 20:23:01

Copyright (c) 1991, 2018, Oracle.  All rights reserved.

Starting /opt/oracle/product/18c/dbhomeXE/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 18.0.0.0.0 - Production
System parameter file is /opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/f065ff3bc8a1/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 18.0.0.0.0 - Production
Start Date                28-NOV-2021 20:23:02
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/f065ff3bc8a1/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
ORACLE instance started.

Total System Global Area 1241512896 bytes
Fixed Size                  8895424 bytes
Variable Size             570425344 bytes
Database Buffers          654311424 bytes
Redo Buffers                7880704 bytes
ORA-03113: end-of-file on communication channel
Process ID: 102
Session ID: 20 Serial number: 38017
```

Any idea whats going on?

**Comment by gvenzl** [comment] 2021-11-28 21:50
Hey @HenrikDK,

Unfortunately, there is not enough information in the docker logs output to determine the cause of that issue.

Could you please provide me with a `docker info` and also the last couple of lines in the database alert log inside the container via `docker exec oxsql tail -n 50 /opt/oracle/diag/rdbms/xe/XE/trace/alert_XE.log`?
That should have more information as to what is going on under the hood.

Thanks,

**Comment by HenrikDK** [comment] 2021-11-29 00:12
Hi, sure heres the output, 

[docker-info.txt](https://github.com/gvenzl/oci-oracle-xe/files/7614687/docker-info.txt)

the docker command you provided didn't work since the container was no longer running, but i hadnt deleted the instance so so I did a copy instead:

docker cp f065ff3bc8a1:/opt/oracle/diag/rdbms/xe/XE/trace/alert_XE.log alert_XE.txt

[alert_XE.txt](https://github.com/gvenzl/oci-oracle-xe/files/7614685/alert_XE.txt)

**Comment by gvenzl** [comment] 2021-11-29 00:44
Thanks a lot, @HenrikDK!

Oh yeah, of course :)

It appears that the database terminates deliberately because one of its background processes died:

```
2021-11-28T20:23:28.437947+00:00
PMON (ospid: 35): terminating the instance due to ORA error 12752
Cause - 'Instance is being terminated due to fatal process death (pid: 8, ospid: 49, SA00)'
2021-11-28T20:23:28.448006+00:00
System state dump requested by (instance=1, osid=35 (PMON)), summary=[abnormal instance termination].
System State dumped to trace file /opt/oracle/diag/rdbms/xe/XE/trace/XE_diag_54_20211128202328.trc
```
Looking at the `docker info` output I'm taking a wild guess here that the container does not have enough memory to run:

```
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.94GiB
 Name: docker-desktop
```

The database alone is trying to allocate 2GB for its SGA and PGA memory areas, that would not leave enough memory for any of the processes running and my guess is that the kernel Out of Memory Killer starts to kill processes.
Could you try to increase the memory for Docker to say 3GB (perhaps 2.5GB should already be enough) and see whether this issue still occurs?
Also, if you still have the container on your machine, could you also please get the trace file `/opt/oracle/diag/rdbms/xe/XE/trace/XE_diag_54_20211128202328.trc` out of it?

**Comment by HenrikDK** [comment] 2021-11-29 00:50
Hmm, thought it might be something like that, I've adjusted the memory to 6gb and will try again.

Here's the trace file you requested:
[xe_trc.txt](https://github.com/gvenzl/oci-oracle-xe/files/7614803/xe_trc.txt)
d.

**Comment by HenrikDK** [comment] 2021-11-29 00:55
Looks like its working now, image hasn't exited and I can connect to the DB. Thanks for the help :)

**Comment by gvenzl** [comment] 2021-11-29 01:20
Wohoo, there we go, glad to hear!
3 GB should be plenty for one container btw, but if you have the memory, sure 6GB works as well. :)

I should probably add some memory check into the container startup script, will open an ER for this and close this one.

Thanks and thanks for using these images! :)

**Closed by gvenzl** 2021-11-29 01:20 UTC
Labels: bug, more-info-required
