### ISSUE TITLE
bind volumes in colima doesn't work

### ISSUE THREAD

**Issue by codrutP** [gvenzl/oci-oracle-xe#159] opened 2022-11-18 07:10 UTC
```
colima start --arch x86_64 --mount-type 9p --memory 4 --network-driver slirp --network-address oraxe
mkdir ~/oradata
docker run -d -p 1521:1521 -e ORACLE_PASSWORD=Oracle2022! --user 501:20 -v ~/oradata:/opt/oracle/oradata:rw --name oraxe gvenzl/oracle-xe
```

fails:

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/oracle/container-entrypoint.sh: permission denied: unknown.`

I have tried also with chmod 777 ~/oradata and here I used --user 501:20 which are the uid and gid of my macOS user

**Comment by gvenzl** [comment] 2022-12-03 18:51
Hi @altitudedashboard,

Thanks for using these images!

Hm, there seems to be a permission issue on executing the container entry script itself. Note that it is located in `/opt/oracle`, not `/opt/oracle/oradata` so this has nothing to do with the volume permissions.

Does it work without the `--user...` and volume?

Also the `permission denied: unknown.` is not very assuring here, namely the `unknown` part.

Any other `colima` users here that might have an idea what's going on here?

**Comment by gvenzl** [comment] 2023-03-12 21:57
Hm, does the `--user` parameter change the owner of the directory and underlying files at all?

**Comment by pocelka** [comment] 2023-03-12 23:27
Nope as I wrote, with --user it doesn't work at all.

**Comment by gvenzl** [comment] 2023-08-06 17:18
Possible duplicate of #163.

Hey @pocelka,

There is a possible solution on SO for docker-compose files by using `user` and `group_add`, see: https://stackoverflow.com/a/75219043/3860389

The user and group ids are both `54321`.

Please let us know whether that solves your issue.

**Comment by pocelka** [comment] 2023-08-07 06:07
Unfortunatelly I don't have arm based mac anymore so I can't test this.

**Comment by gvenzl** [comment] 2023-10-14 19:03
Closing issue due to inactiveness.

**Closed by gvenzl** 2023-10-14 19:03 UTC
Labels: help wanted, question
