### ISSUE TITLE
Is it possible to make this run on a m1 mac?

### ISSUE THREAD

**Issue by RuneLind** [gvenzl/oci-oracle-xe#76] opened 2022-01-06 22:22 UTC
I am trying 
```
docker run -it --platform linux/amd64 -p 1521:1521 -e ORACLE_PASSWORD=oracle gvenzl/oracle-xe:18.4.0-slim
```
And it failed to start
```
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
ERROR:
ORA-12547: TNS:lost contact


SP2-0306: Invalid option.
```

**Comment by kubo** [comment] 2022-01-07 09:50
duplicate of #63

**Closed** 2022-01-07 14:11 UTC
